version: '3.7'

services:
  adless-weather-server:
    image: adless-weather-server
    container_name: adless-weather-server
    build:
      context: .
      dockerfile: docker/server/Dockerfile
      target: dev-stage
    command: ["npm", "run", "dev"]
    networks:
      - adless-weather
    volumes:
      - "./server:/usr/src/server"
      - "/usr/src/server/node_modules"
    env_file:
      - server/.env
    ports:
      - '3000:8080'

  adless-weather-app:
    image: adless-weather-app
    container_name: adless-weather-app
    build:
      context: .
      dockerfile: docker/app/Dockerfile
      target: dev-stage
    command: ["npm", "run", "start"]
    networks:
      - adless-weather
    volumes:
      - "./app:/usr/src/app"
      - "/usr/src/app/node_modules"
    env_file:
      - app/.env
    ports:
      - '3001:8080'

  redis-cache:
    image: "redis:4.0.14"
    container_name: redis-cache
    networks:
      - adless-weather
    ports:
      - 32773:6379
networks:
  adless-weather:
    external: true